#!/bin/sh
jsfiles=$(git diff --cached --name-only --diff-filter=ACM | grep '\.jsx\?$' | tr '\n' ' ')
[ -z "$jsfiles" ] && exit 0

node_modules/.bin/prettier-eslint --write $jsfiles --eslint-config-path .eslintrc
git add $jsfiles
